#!/bin/bash
# this example is auto generated by the "guide" command
#SBATCH --job-name=cu_relax
#SBATCH --time=0-00:30      # Max time (DD-HH:MM)
#SBATCH --cpus-per-task=6   # Number of CPUs
#SBATCH --mem=6G            # Memory per node
module load class-simulations

/scic/app/cpu/lammps/2025-04-02/bin/lmp -in Fe.cu