#!/bin/bash
# this example is auto generated by the "guide" command
#SBATCH --job-name=Lab4	# Job Name
#SBATCH --time=0-01:00      # Max time (DD-HH:MM)
#SBATCH --cpus-per-task=16   # Number of CPUs
#SBATCH --mem=8G            # Memory per cpu
module load class-simulations

srun /scic/app/cpu/lammps/2025-04-02/bin/lmp < in.Argon

