#!/bin/bash
# this example is auto generated by the "guide" command
#SBATCH --job-name=LiMn2O4
#SBATCH --time=1-10:00      # Max time (DD-HH:MM)
#SBATCH --cpus-per-task=6   # Number of CPUs
##SBATCH --mem=6G            # Memory per node
module load class-simulations

/scic/app/cpu/lammps/2025-04-02/bin/lmp -in in1400.LiMnO
